# Generated by Django 4.0.6 on 2022-07-28 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_area_created_at_area_updated_at_bouquet_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='invoice_created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
